# Generated by Django 5.2.4 on 2025-09-07 07:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='login_data',
            fields=[
                ('us_in', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('username', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=30)),
                ('passwrd', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='info_db',
            fields=[
                ('info_acc_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('firstnme', models.CharField(max_length=30)),
                ('middlenme', models.CharField(max_length=30)),
                ('lastnme', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('dob', models.DateField()),
                ('phone', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('pin', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('organizations', models.CharField(max_length=150)),
                ('user_inf_pi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='passmanager_app.login_data')),
            ],
        ),
        migrations.CreateModel(
            name='notes_db',
            fields=[
                ('notes_acc_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('note_name', models.CharField(max_length=50)),
                ('user_inf_notes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='passmanager_app.login_data')),
            ],
        ),
        migrations.CreateModel(
            name='notes_con',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_con', models.TextField()),
                ('user_idf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='passmanager_app.notes_db')),
            ],
        ),
        migrations.CreateModel(
            name='user_dt',
            fields=[
                ('acc_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('site', models.CharField(max_length=50)),
                ('link', models.URLField(max_length=100)),
                ('user_name', models.CharField(max_length=50, null=True)),
                ('password', models.CharField(max_length=400)),
                ('category', models.CharField(max_length=50, null=True)),
                ('Notes', models.CharField(max_length=500, null=True)),
                ('user_inf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='passmanager_app.login_data')),
            ],
        ),
    ]
