# Generated by Django 5.2.4 on 2025-09-19 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passmanager_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info_db',
            name='dob',
            field=models.DateField(null=True),
        ),
    ]
